site_name: reflectance

theme:
  name: "material"  
  features:
    - content.code.copy
 
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/g-patin/reflectance
      name: GitHub

  
nav:
  - index.md
  - installation.md  
  
plugins:
  - search
  - mkdocs-jupyter
  - mkdocstrings:
      handlers:
        python:
          paths: ['src']  # Make sure mkdocstrings looks in the 'src' directory
          
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true
      
extra_css:
  - css/custom.css
  
extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
